## playground

In [8]:
import numpy as np
%load_ext autoreload
%autoreload 2

model testing

In [3]:
from model_detection import Model

In [40]:
m = Model.loadModel("./data/test/cookies_ORB.yml")

In [43]:
m.getKeypoints().shape

(5914, 7)

In [44]:
m.get3DPoints()[0]

array([5.8165207, 6.5905914, 7.5      ], dtype=float32)

In [42]:
m.getDescriptors().shape

(5914, 32)

Mesh testing

In [49]:
from model_detection import Mesh

In [55]:
m = Mesh.loadMesh("./data/test/box.ply")

In [56]:
m.vertices_

array([[ 0. ,  0. ,  0. ],
       [ 0. , 25.8,  0. ],
       [18.9,  0. ,  0. ],
       [18.9, 25.8,  0. ],
       [ 0. ,  0. ,  7.5],
       [ 0. , 25.8,  7.5],
       [18.9,  0. ,  7.5],
       [18.9, 25.8,  7.5]])

In [57]:
m.triangles_

array([[5., 1., 0.],
       [5., 4., 0.],
       [4., 0., 2.],
       [4., 6., 2.],
       [7., 5., 4.],
       [7., 6., 4.],
       [3., 2., 1.],
       [1., 2., 0.],
       [5., 7., 1.],
       [7., 1., 3.],
       [7., 6., 3.],
       [6., 3., 2.]])

## testing util functions

draw points

In [10]:
import cv2 as cv
from util import *

In [24]:
img = cv.imread('./data/test/resized_IMG_3875.jpg')

# show image
drawPoints(img, [(100,200)], "yellow")
cv.imshow('image',img)
cv.waitKey(0) #wait for any key

cv.destroyAllWindows() #close the image window


draw lines

In [30]:
# show image
draw3DCoordinateAxes(img, [(100,200),(150,200), (50, 230), (150, 150)])
cv.imshow('image',img)
cv.waitKey(0) #wait for any key

cv.destroyAllWindows() #close the image window
